"""empty message

Revision ID: f4822306088d
Revises:
Create Date: 2018-09-11 14:51:30.715091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4822306088d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nickname')
    )
    op.create_table('servers',
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('endpoint')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('elapsed_time', sa.Interval(), nullable=False),
    sa.Column('server_endpoint', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['server_endpoint'], ['servers.endpoint'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreboards',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_nickname', sa.String(length=128), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_nickname'], ['players.nickname'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreboards')
    op.drop_table('matches')
    op.drop_table('servers')
    op.drop_table('players')
    # ### end Alembic commands ###
